### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by LemADEC** [EleC0TroN/EndReborn#2]
As of 0.1.6, server will not boot due to client side classes being missing:
```
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.Render
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
>       at endreborn.util.handlers.RenderHandler.registerEntityRenders(RenderHandler.java:16) ~[RenderHandler.class:?]
>       at endreborn.util.handlers.RegistryHandler.preInitRegistries(RegistryHandler.java:57) ~[RegistryHandler.class:?]
>       at endreborn.mod.RebornofEnd.preInit(RebornofEnd.java:35) ~[RebornofEnd.class:?]
```

**Comment by EleC0TroN** [comment]
This is because of the rendering of the mobs, but why...

**Comment by EleC0TroN** [comment]
I will try to fix it, but I do not know how

**Comment by LemADEC** [comment]
That line RenderHandler.java:16 is loading a class that refers to net.minecraft.client.renderer.entity.Render.
The latest is client side and should never be loaded server side.

**Comment by LemADEC** [comment]
To be fair, there's no render server side, so the whole RenderHandler shouldn't be called on the server. This is typically done by moving it to the ClientProxy.

**Comment by aksansai** [comment]
Same problem.

**Comment by EleC0TroN** [comment]
I still can not do anything with the mod, because there was a breakdown of the PC.

**Comment by EleC0TroN** [comment]
I don't know yet when I can return

**Comment by EleC0TroN** [comment]
Done
